# Generated by Django 3.2 on 2021-08-17 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-text'], 'verbose_name_plural': 'Todo"s'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='added_text',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 13, 30, 56, 13359)),
        ),
    ]
