# Generated by Django 3.2 on 2021-08-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210817_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='added_text',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 13, 43, 27, 843539)),
        ),
    ]
